apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: mariadb
    release: prometheus
  name: mariadb
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - database
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: mariadb-galera
      app.kubernetes.io/name: mariadb-galera