apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  name: data-mariadb-galera-pv-volume-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-mariadb-galera-1
    namespace: database
  local:
    path: /data/data-mariadb-galera/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k-worker-n1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
